%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 956.846161
Camera.fy: 956.865873
Camera.cx: 960.575468
Camera.cy: 538.050923

Camera.k1: -0.003275
Camera.k2: 0.001705
Camera.p1: -0.000480
Camera.p2: 0.000439
Camera.k3: 0.000000

Camera.width: 1920
Camera.height: 1080

# Camera frames per second 
Camera.fps: 30.0

# IR projector baseline times fx (aprox.)
Camera.bf: 95.68

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 20.0

# Deptmap values factor 
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
#Viewer.KeyFrameSize: 0.05
#Viewer.KeyFrameLineWidth: 1
#Viewer.GraphLineWidth: 0.9
#Viewer.PointSize:2
#Viewer.CameraSize: 0.08
#Viewer.CameraLineWidth: 3
#Viewer.ViewpointX: 0
#Viewer.ViewpointY: -0.7
#Viewer.ViewpointZ: -1.8
#Viewer.ViewpointF: 500

PointCloudMapping.Resolution: 0.01
